[build]
  base = "site/"
  command = "hugo --gc --minify"
  publish = "site/public"

[context.production.environment]
HUGO_VERSION = "0.83.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.83.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.83.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.83.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[build.processing]
  skip_processing = false # -> Enable processing
[build.processing.css]
  bundle = true # -> Concatenate consecutive CSS files together to reduce HTTP requests.
  minify = true # -> Run CSS through a minifier to reduce file size.
[build.processing.js]
  bundle = true # -> Concatenate consecutive JS files together to reduce HTTP requests.
  minify = true # -> Run JS through a minifier to reduce file size.
[build.processing.images]
  compress = true # -> Run all images through lossless image compression.

# Reference documentation
# Optimization blog post: https://www.netlify.com/blog/2019/08/05/control-your-asset-optimization-settings-from-netlify.toml/
# How to guide: https://docs.netlify.com/configure-builds/file-based-configuration/#post-processing

# Redirect /quickstart/sesame.yaml to the deployment that matches :latest.
#
# kubectl apply https://projectsesame.io/quickstart/sesame.yaml
[[redirects]]
  from = "/quickstart/sesame.yaml"
  to = "https://raw.githubusercontent.com/projectsesame/sesame/release-1.19/examples/render/sesame.yaml"
  status = 302

# Redirect versioned quickstarts so that they can easily be referenced by
# users or for upgrade testing.
#
# kubectl apply https://projectsesame.io/quickstart/v1.4.0/sesame.yaml
[[redirects]]
  from = "/quickstart/*/sesame.yaml"
  to = "https://raw.githubusercontent.com/projectsesame/sesame/:splat/examples/render/sesame.yaml"
  status = 302

# Redirect /quickstart/operator.yaml to the deployment that matches :latest.
#
# kubectl apply https://projectsesame.io/quickstart/operator.yaml
[[redirects]]
from = "/quickstart/operator.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/release-1.19/examples/operator/operator.yaml"
status = 302

# Redirect versioned quickstarts so that they can easily be referenced by
# users or for upgrade testing.
#
# kubectl apply https://projectsesame.io/quickstart/v1.11.0/operator.yaml
[[redirects]]
from = "/quickstart/*/operator.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/:splat/examples/operator/operator.yaml"
status = 302

# Redirect /quickstart/sesame-custom-resource.yaml to the Sesame custom resource that matches :latest.
#
# kubectl apply https://projectsesame.io/quickstart/sesame-custom-resource.yaml
[[redirects]]
from = "/quickstart/ssame-custom-resource.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/release-1.19/examples/sesame/sesame.yaml"
status = 302

# Redirect versioned quickstarts so that they can easily be referenced by
# users or for upgrade testing.
#
# kubectl apply https://projectsesame.io/quickstart/v1.11.0/sesame-custom-resource.yaml
[[redirects]]
from = "/quickstart/*/sesame-custom-resource.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/:splat/examples/sesame/sesame.yaml"
status = 302

# Redirect /quickstart/gateway.yaml to the example Gateway manifest that matches :latest.
#
# kubectl apply https://projectsesame.io/quickstart/gateway.yaml
[[redirects]]
from = "/quickstart/gateway.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/release-1.19/examples/gateway/gateway.yaml"
status = 302

# Redirect /quickstart/sesame-gateway.yaml to the example Sesame-Gateway manifest that matches :latest.
#
# kubectl apply https://projectsesame.io/quickstart/sesame-gateway.yaml
[[redirects]]
from = "/quickstart/sesame-gateway.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame/release-1.19/examples/render/sesame-gateway.yaml"
status = 302

# Redirect versioned quickstarts so that they can easily be referenced by
# users or for upgrade testing.
#
# kubectl apply https://projectsesame.io/quickstart/v1.11.0/gateway.yaml
[[redirects]]
from = "/quickstart/*/gateway.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/:splat/examples/gateway/gateway.yaml"
status = 302

# Redirect /quickstart/gateway-nodeport.yaml to the example Gateway manifest that matches :latest.
#
# kubectl apply https://projectsesame.io/quickstart/gateway-nodeport.yaml
[[redirects]]
from = "/quickstart/gateway-nodeport.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/release-1.19/examples/gateway/gateway-nodeport.yaml"
status = 302

# Redirect versioned quickstarts so that they can easily be referenced by
# users or for upgrade testing.
#
# kubectl apply https://projectsesame.io/quickstart/v1.11.0/gateway-nodeport.yaml
[[redirects]]
from = "/quickstart/*/gateway-nodeport.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/:splat/examples/gateway/gateway-nodeport.yaml"
status = 302

# Redirect /quickstart/kuard.yaml to the example Kuard manifest that matches :latest.
#
# kubectl apply https://projectsesame.io/quickstart/kuard.yaml
[[redirects]]
from = "/quickstart/kuard.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/release-1.19/examples/gateway/kuard/kuard.yaml"
status = 302

# Redirect versioned quickstarts so that they can easily be referenced by
# users or for upgrade testing.
#
# kubectl apply https://projectsesame.io/quickstart/v1.11.0/kuard.yaml
[[redirects]]
from = "/quickstart/*/kuard.yaml"
to = "https://raw.githubusercontent.com/projectsesame/sesame-operator/:splat/examples/gateway/kuard/kuard.yaml"
status = 302
