---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sesame-certgen
  namespace: projectsesame
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sesame
  namespace: projectsesame
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sesame-certgen
subjects:
- kind: ServiceAccount
  name: sesame-certgen
  namespace: projectsesame
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sesame-certgen
  namespace: projectsesame
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sesame-certgen-main
  namespace: projectsesame
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        app: "sesame-certgen"
    spec:
      containers:
      - name: sesame
        image: ghcr.io/projectsesame/sesame:main
        imagePullPolicy: Always
        command:
        - sesame
        - certgen
        - --kube
        - --incluster
        - --overwrite
        - --secrets-format=compact
        - --namespace=$(SESAME_NAMESPACE)
        env:
        - name: SESAME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: Never
      serviceAccountName: sesame-certgen
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
  parallelism: 1
  completions: 1
  backoffLimit: 1
